name: Crave Builder

on:
  workflow_dispatch:
    inputs:
      command:
        description: 'Crave Target Build Commands'
        required: true
        default: 'crave run -- "echo Hello"'

jobs:
  crave_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'

      - name: Install Crave CLI
        run: |
          mkdir -p $HOME/bin
          curl -sL https://raw.githubusercontent.com/accupara/crave/master/get_crave.sh | bash -s -- $HOME/bin
          echo "$HOME/bin" >> $GITHUB_PATH

      - name: Configure Crave
        run: |
          mkdir -p $HOME/.crave
          echo '{
            "username": "${{ secrets.CRAVE_USERNAME }}",
            "auth": "${{ secrets.CRAVE_TOKEN }}"
          }' > $HOME/.crave/crave.conf

      - name: Execute Crave Command
        run: |
          eval "${{ github.event.inputs.command }}"
